### ISSUE TITLE
No package metadata was found

### ISSUE THREAD

**Issue by KerstenBreuer** [CompEpigen/CWLab#173]
Fix metadata availablity issue occuring in dev_elixir docker container:

```
Traceback (most recent call last):
  File "/usr/bin/cwlab", line 33, in <module>
    sys.exit(load_entry_point('cwlab', 'console_scripts', 'cwlab')())
  File "/usr/bin/cwlab", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 558, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 215, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for cwlab
```

**Comment by KerstenBreuer** [comment]
has been fixed
