### ISSUE TITLE
Public docker-dev image does not start

### ISSUE THREAD

**Issue by lukasjelonek** [CompEpigen/CWLab#201]
The docker container does not start due to version conflicts:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 39.0.1 (/usr/lib/python3/dist-packages), Requirement.parse('setuptools>=39.1.0'), {'miniwdl'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cwlab", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 39.0.1 (/usr/lib/python3/dist-packages), Requirement.parse('setuptools>=39.1.0'), {'miniwdl'})
```

Tested on: Docker for Windows and docker.io on Ubuntu 20.04
Commands to reproduce:
```bash
docker run --name cwlab -d compepigen/cwlab:dev
docker logs cwlab

# cleanup
docker rm cwlab
```

**Comment by lukasjelonek** [comment]
Are there reasons not to use the latest (stable) versions of `ubuntu`, `singularity` and `cwltool` in the image? By updating these in ./docker/dev/Dockerfile` I at got a container that starts and serves requests. See lukasjelonek/CWLab@c3f57d1

**Comment by KerstenBreuer** [comment]
Hi @lukasjelonek,

thanks a lot for reporting this bug. We also yesterday discovered that some dependency conflicts arose. Great that you found a solution to that.
You may merge it to the development branch at your will.

Thanks a lot and best wishes,
Kersten

**Comment by lukasjelonek** [comment]
The newly build public image works 👍
